version: '3.8'
services:
  app:
    build: .
    container_name: hr-container
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./config/database.php:/var/www/html/hr-app/config/database.php
