server {
    listen 80;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    
    ssl_certificate /etc/ssl/ytech/ytech.crt;
    ssl_certificate_key /etc/ssl/ytech/ytech.key;
    ssl_protocols TLSv1.3;
    
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    add_header Strict-Transport-Security "max-age=31536000";

    # Zabbix
    location /zabbix/ {
        proxy_pass http://zabbix-web:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Bitwarden
    location /bitwarden/ {
        proxy_pass http://bitwarden:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
    }

    # Default → Zabbix
    location / {
        proxy_pass http://zabbix-web:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
